//! Dictionary and type metadata ported from QMK's mejiro_verb.c.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum VerbType {
    Godan,
    Kami,
    Simo,
    Kahen,
    Special,
}

#[derive(Clone, Copy, Debug)]
pub(crate) struct VerbEntry {
    pub(crate) stroke: &'static str,
    pub(crate) stem: &'static str,
    pub(crate) row: char,
    pub(crate) kind: VerbType,
}

pub(crate) const VERB_DICTIONARY: &[VerbEntry] = &[
    VerbEntry {
        stroke: "I-K",
        stem: "",
        row: 'x',
        kind: VerbType::Special,
    },
    VerbEntry {
        stroke: "A-",
        stem: "",
        row: 'x',
        kind: VerbType::Special,
    },
    VerbEntry {
        stroke: "K-",
        stem: "",
        row: 'x',
        kind: VerbType::Kahen,
    },
    VerbEntry {
        stroke: "A-STU",
        stem: "ある",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-TNA",
        stem: "いただ",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-TNA",
        stem: "いだ",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "U-KNAU",
        stem: "うご",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-YA",
        stem: "かがや",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KI-KNA",
        stem: "きがつ",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KI-TNU",
        stem: "きづ",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SI-KNAU",
        stem: "しご",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-TA",
        stem: "たた",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-TNU",
        stem: "つづ",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NAU-SNAU",
        stem: "のぞ",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-TA",
        stem: "はた",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-STA",
        stem: "はたら",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKI-STA",
        stem: "ひら",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNI-KNA",
        stem: "みが",
        row: 'k',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-SAU",
        stem: "いそ",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-SIA",
        stem: "かせ",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-TU",
        stem: "かつ",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SA-SA",
        stem: "ささ",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-NA",
        stem: "つな",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKU-SA",
        stem: "ふさ",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKU-SIA",
        stem: "ふせ",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNA-TA",
        stem: "また",
        row: 'g',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "A-KA",
        stem: "あか",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-KA",
        stem: "いか",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-TA",
        stem: "いた",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "AU-TAU",
        stem: "おと",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-KA",
        stem: "かか",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-KU",
        stem: "かく",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KU-STA",
        stem: "くら",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KAU-STAU",
        stem: "ころ",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KAU-SKA",
        stem: "こわ",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SA-KNA",
        stem: "さが",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SI-SKNIA",
        stem: "しめ",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SNU-STA",
        stem: "ずら",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-AU",
        stem: "たお",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TNA-",
        stem: "だ",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-TKNU",
        stem: "つぶ",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TIA-STA",
        stem: "てら",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NA-AU",
        stem: "なお",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NI-KNA",
        stem: "にが",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NAU-TKNA",
        stem: "のば",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-NA",
        stem: "はな",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-KNA",
        stem: "はが",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNA-KA",
        stem: "まか",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNI-TA",
        stem: "みた",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNI-NA",
        stem: "みな",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNI-SKNA",
        stem: "みまわ",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNI-SKA",
        stem: "みわた",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "YU-STA",
        stem: "ゆら",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKA-TA",
        stem: "わた",
        row: 's',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "U-KNA",
        stem: "うが",
        row: 't',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SAU-TNA",
        stem: "そだ",
        row: 't',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-SKNAU",
        stem: "たも",
        row: 't',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNIA-TNA",
        stem: "めだ",
        row: 't',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "A-SAU",
        stem: "あそ",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "IA-STA",
        stem: "えら",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "AU-YAU",
        stem: "およ",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KAU-STAU",
        stem: "ころ",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NA-STA",
        stem: "なら",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-KAU",
        stem: "はこ",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKAU-STAU",
        stem: "ほろ",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNA-NA",
        stem: "まな",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNU-SU",
        stem: "むす",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "YAU-STAU",
        stem: "よろこ",
        row: 'b',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-NA",
        stem: "いな",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "U-STA",
        stem: "うらや",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-KNA",
        stem: "かが",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-SU",
        stem: "かす",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SI-SNU",
        stem: "しず",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SU-SU",
        stem: "すす",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-NAU",
        stem: "たの",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TIU-TKNA",
        stem: "ついば",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-TU",
        stem: "つつ",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-SKNA",
        stem: "つま",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NA-YA",
        stem: "なや",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NU-SU",
        stem: "ぬす",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NAU-SNAU",
        stem: "のぞ",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-SA",
        stem: "はさ",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKI-KAU",
        stem: "ひっこ",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKU-KU",
        stem: "ふく",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKAU-TKAU",
        stem: "ほほえ",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "YA-SU",
        stem: "やす",
        row: 'm',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-",
        stem: "い",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-IA",
        stem: "かえ",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-KNI",
        stem: "かぎ",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KNA-TKNA",
        stem: "がんば",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KNA-",
        stem: "がんば",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KI-I",
        stem: "きにい",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KI-NA",
        stem: "きにな",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KU-TNA",
        stem: "くださ",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KIA-",
        stem: "け",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KAU-TAU",
        stem: "ことな",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SYA-TKNIA",
        stem: "しゃべ",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SU-TKNIA",
        stem: "すべ",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "T-KA",
        stem: "たすか",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-SNU",
        stem: "たずさわ",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NA-",
        stem: "な",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKY-",
        stem: "はい",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-SI",
        stem: "はし",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-TKNA",
        stem: "はばか",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "YA-",
        stem: "や",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "-YA",
        stem: "や",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKA-",
        stem: "わか",
        row: 'r',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "-A",
        stem: "あ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "A-STA",
        stem: "あら",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "A-SAU",
        stem: "あらそ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "IU-",
        stem: "い",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-SNA",
        stem: "いざな",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "I-SKA",
        stem: "いわ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "U-SI",
        stem: "うしな",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "U-TA",
        stem: "うた",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "U-KNA",
        stem: "うたが",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "U-YA",
        stem: "うやま",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "AU-KAU",
        stem: "おこな",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "AU-SKNAU",
        stem: "おも",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "AU-",
        stem: "おも",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-NA",
        stem: "かな",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KA-SKNA",
        stem: "かま",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "KU-STU",
        stem: "くる",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SI-A",
        stem: "しあ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SI-TA",
        stem: "したが",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SI-SKNA",
        stem: "しま",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SU-KU",
        stem: "すく",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SAU-STAU",
        stem: "そろ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TA-TA",
        stem: "たたか",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TI-KA",
        stem: "ちか",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TI-KNA",
        stem: "ちが",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-KA",
        stem: "つか",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-TI",
        stem: "つちか",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TU-TNAU",
        stem: "つど",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TIA-STA",
        stem: "てら",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TNIA-A",
        stem: "であ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TAU-NA",
        stem: "ともな",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NA-STA",
        stem: "なら",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NI-A",
        stem: "にあ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NI-SKA",
        stem: "にぎわ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NIA-KNA",
        stem: "ねが",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "NAU-STAU",
        stem: "のろ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKA-STA",
        stem: "はら",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "TKI-STAU",
        stem: "ひろ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNA-TAU",
        stem: "まと",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNI-A",
        stem: "みあ",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNU-KA",
        stem: "むか",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKNAU-STA",
        stem: "もら",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "SKA-STA",
        stem: "わら",
        row: 'w',
        kind: VerbType::Godan,
    },
    VerbEntry {
        stroke: "IA-SNI",
        stem: "えん",
        row: 'z',
        kind: VerbType::Kami,
    },
    VerbEntry {
        stroke: "KA-SNI",
        stem: "かん",
        row: 'z',
        kind: VerbType::Kami,
    },
    VerbEntry {
        stroke: "KI-SNI",
        stem: "きん",
        row: 'z',
        kind: VerbType::Kami,
    },
    VerbEntry {
        stroke: "SI-SNI",
        stem: "しん",
        row: 'z',
        kind: VerbType::Kami,
    },
    VerbEntry {
        stroke: "TNA-SNI",
        stem: "だん",
        row: 'z',
        kind: VerbType::Kami,
    },
    VerbEntry {
        stroke: "KA-SKNI",
        stem: "かんが",
        row: 'm',
        kind: VerbType::Kami,
    },
    VerbEntry {
        stroke: "KI-SKAU",
        stem: "きをつ",
        row: 'k',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "T-KIA",
        stem: "たす",
        row: 'k',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "TU-TN",
        stem: "つづ",
        row: 'k',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "TN-KIA",
        stem: "つづ",
        row: 'k',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "K-KNIA",
        stem: "かか",
        row: 'g',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "A-SKA",
        stem: "あわ",
        row: 's',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "SKNA-KA",
        stem: "まか",
        row: 's',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "TN-",
        stem: "",
        row: 'd',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "KU-STA",
        stem: "くら",
        row: 'b',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "SI-STA",
        stem: "しら",
        row: 'b',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "SA-TNA",
        stem: "さだ",
        row: 'm',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "TA-SI",
        stem: "たしか",
        row: 'm',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "TKA-SNI",
        stem: "はじ",
        row: 'm',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "SKNAU-TAU",
        stem: "もと",
        row: 'm',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "U-SKNAU",
        stem: "うも",
        row: 'r',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "KAU-STIA",
        stem: "こわ",
        row: 'r',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "NA-KNA",
        stem: "なが",
        row: 'r',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "TKA-SNU",
        stem: "はず",
        row: 'r',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "SKA-SU",
        stem: "わす",
        row: 'r',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "AU-SA",
        stem: "おさ",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "AU-SI",
        stem: "おし",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "AU-TKNAU",
        stem: "おぼ",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "KA-KNA",
        stem: "かんが",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "KA-",
        stem: "かんが",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "KI-TA",
        stem: "きた",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "KU-SKA",
        stem: "くわ",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "KAU-TA",
        stem: "こた",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "SA-SA",
        stem: "ささ",
        row: 'w',
        kind: VerbType::Simo,
    },
    VerbEntry {
        stroke: "SKNA-KNA",
        stem: "まちが",
        row: 'w',
        kind: VerbType::Simo,
    },
];
